name: Review Entry

on:
  issue_comment:
    types: [created]

env:
  PR_AUTHOR: ${{ github.event.issue.user.login }}
  COMMENT_AUTHOR: ${{ github.event.comment.user.login }}

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
      verified: ${{ steps.verify.outputs.verify }}

    steps:
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: check_accept
      with:
        prefix_only: true
        trigger: '!accept'
        # reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'
          
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: check_reject
      with:
        prefix_only: true
        trigger: '!reject'
        # reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'
        
    - uses: actions/github-script@v3
      id: get_pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.pulls.get(request)
            return result.data
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
    
    - name: Checkout PR
      uses: actions/checkout@v3
      with:
        path: repo
        repository: ${{ fromJSON(steps.get_pr.outputs.result).head.repo.full_name }}
        ref: ${{ fromJSON(steps.get_pr.outputs.result).head.sha }}
        
    - name: Checkout Indexer
      uses: actions/checkout@v3
      with:
        path: code

    - name: Checkout Index
      uses: actions/checkout@v3
      with:
        repository: geode-sdk/mods
        path: index
        token: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - id: verify
      working-directory: ${{ github.workspace }}/index
      run: |
        echo VERIFY=`python3 ${{ github.workspace }}/code/.github/verify.py $COMMENT_AUTHOR` >> $GITHUB_ENV

    - if: ${{ env.VERIFY == 'true' && steps.check_accept.outputs.triggered == 'true' }}
      id: check
      working-directory: repo
      shell: bash
      run: |
        url=`git remote get-url origin`
        branch=`git rev-parse HEAD`
        dirs=`ls -1d */`
        cd ../index
        python3 ../code/.github/reset-repo.py $url
        echo "MESSAGE<<EOF" >> $GITHUB_ENV
        for i in $dirs; do
          python3 ../code/.github/add-entry.py ../repo/$i $PR_AUTHOR $url/raw/$branch/$i >> $GITHUB_ENV
        done
        echo -n "EOF" >> $GITHUB_ENV
        
    - if: ${{ env.VERIFY == 'true' && (steps.check_reject.outputs.triggered == 'true' || steps.check_accept.outputs.triggered == 'true')}}
      name: Close PR
      uses: peter-evans/close-pull@v2
      with:
        pull-request-number: ${{ github.event.issue.number }}
        comment: ${{ env.MESSAGE }}

    - if: ${{ env.VERIFY == 'true' && steps.check_accept.outputs.triggered == 'true'}}
      name: Commit, push to index
      shell: bash
      working-directory: ${{ github.workspace }}/index
      run: |
        git config --local user.email "${{ secrets.GEODE_BOT_EMAIL }}"
        git config --local user.name "GeodeBot"
        git add -A
        git commit -m "Update from $PR_AUTHOR"
        git remote set-url origin "https://GeodeBot:${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}@github.com/geode-sdk/mods.git"
        git push -u origin main || true
        
